In [1]:
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import LinearSVC, SVC
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.model_selection import KFold
from sklearn.multiclass import OneVsRestClassifier
from sklearn import preprocessing
from sklearn.calibration import CalibratedClassifierCV
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
import codecs
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import GridSearchCV
from time import time
from scipy.stats import randint as sp_randint
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

In [46]:
corpus = list()
ylabels = list()
test = list()

path = '/home/clau/Documents/journalists2017_personas/emotions/'

f = codecs.open(path+'train.txt', 'r')
for line in f:
    corpus.append(line)
f.close()

f1 = codecs.open(path+'target.txt', 'r')
for line in f1:
    thisLine = list()
    thisLine.append(line.strip())
    ylabels.append(thisLine)
f1.close()


with open(path+'test_split_1.txt') as textfile1:
    for x in textfile1:
        x = x.strip()
        test.append(x)

X_train = np.array(corpus)

X_test = np.array(test)

lb = preprocessing.MultiLabelBinarizer()
Y = lb.fit_transform(ylabels)
svm = LinearSVC()

classifier = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('tfidf', TfidfTransformer()),
    ('clf', OneVsRestClassifier(CalibratedClassifierCV(svm)))])

classifier.fit(X_train, Y)
predicted = classifier.predict(X_test)
all_labels = lb.inverse_transform(predicted)

for item, labels in zip(X_test, all_labels):
    print('%s \t %s' % (item, ', '.join(labels)))

@ReaganBattalion That's a terrible thing to accuse Scott Baio of. 	 2
Stars, when you shine,\nYou know how I feel.\nScent of the pine, \nYou know how I feel.\nFreedom is mine,\nI know how I feel.\nI'm feelin' good. 	 4
My life went from happy to unhappy.. 	 3, 4
Northampton are awful 🙈 	 2
Realest ever, relentless ever, inevitable that I win. 	 1
@r0Ils ppl get triggered over u smiling they're irrelevant 	 3
@ArcticFantasy I would have almost took offense to this if I actually snapped you 	 1
...at your age, the heyday in the blood is tame...' @TheArtofCharm #shakespeareaninsults #hamlet #elizabethan #williamshakespeare 	 3
On @Varneyco/@FoxBusiness to talk latest on #Chelsea Bombing + #Ahmad_Khan_Rahami's trips to #Afghanistan/#Pakistan #tcot #terror 	 2
Each day is what you make of it! #goals #challenges #business #goals #optimism #happy #success #photographer #photography #ThursdayThoughts 	 3
Southend players always haunt Man U 	 2
#Awareness seek #shelter .#Letgo Old #habit of cha

In [50]:
corpus = list()
ylabels = list()
test = list()

path = '/home/clau/Documents/journalists2017_personas/emotions/'

f = codecs.open(path+'train.txt', 'r')
for line in f:
    corpus.append(line)
f.close()

f1 = codecs.open(path+'target.txt', 'r')
for line in f1:
    thisLine = list()
    thisLine.append(line.strip())
    ylabels.append(thisLine)
f1.close()


with open(path+'test_split_1.txt') as textfile1:
    for x in textfile1:
        x = x.strip()
        test.append(x)

X_train = np.array(corpus)

X_test = np.array(test)

lb = preprocessing.MultiLabelBinarizer()
Y = lb.fit_transform(ylabels)

classifier = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('tfidf', TfidfTransformer()),
    ('clf', OneVsRestClassifier(RandomForestClassifier(n_estimators=500)))])

classifier.fit(X_train, Y)
predicted = classifier.predict(X_test)
all_labels = lb.inverse_transform(predicted)

for item, labels in zip(X_test, all_labels):
    print('%s \t %s' % (item, ', '.join(labels)))

@ReaganBattalion That's a terrible thing to accuse Scott Baio of. 	 2
Stars, when you shine,\nYou know how I feel.\nScent of the pine, \nYou know how I feel.\nFreedom is mine,\nI know how I feel.\nI'm feelin' good. 	 4
My life went from happy to unhappy.. 	 3, 4
Northampton are awful 🙈 	 2
Realest ever, relentless ever, inevitable that I win. 	 1
@r0Ils ppl get triggered over u smiling they're irrelevant 	 3
@ArcticFantasy I would have almost took offense to this if I actually snapped you 	 1
...at your age, the heyday in the blood is tame...' @TheArtofCharm #shakespeareaninsults #hamlet #elizabethan #williamshakespeare 	 3
On @Varneyco/@FoxBusiness to talk latest on #Chelsea Bombing + #Ahmad_Khan_Rahami's trips to #Afghanistan/#Pakistan #tcot #terror 	 2
Each day is what you make of it! #goals #challenges #business #goals #optimism #happy #success #photographer #photography #ThursdayThoughts 	 3
Southend players always haunt Man U 	 
#Awareness seek #shelter .#Letgo Old #habit of chas

In [2]:
corpus = list()
ylabels = list()
test = list()

path = '/home/clau/Documents/journalists2017_personas/emotions/'

f = codecs.open(path+'full_train.txt', 'r')
for line in f:
    corpus.append(line.strip())
f.close()

f1 = codecs.open(path+'full_target.txt', 'r')
for line in f1:
    thisLine = list()
    thisLine.append(line.strip())
    ylabels.append(thisLine)
f1.close()

X = np.array(corpus)
y = np.array(ylabels)

lb = preprocessing.MultiLabelBinarizer()
Y = lb.fit_transform(ylabels)

model = LinearSVC()

classifier = Pipeline(
    [
        ('vectorizer', CountVectorizer()),
        ('tfidf', TfidfTransformer()),
        ('clf', OneVsRestClassifier(CalibratedClassifierCV(model)))
    ])

kf = KFold(n_splits=10, random_state=None, shuffle=False)
kf.get_n_splits(X) # returns the number of splitting iterations in the cross-validator

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y[train_index], Y[test_index]

    classifier.fit(X_train, y_train)
    y_predicted = classifier.predict(X_test)
    y_pred = lb.inverse_transform(y_predicted)
    print(classification_report(y_test, y_predicted))
    #print(y_pred)
    print('=========')

             precision    recall  f1-score   support

          0       0.92      0.85      0.88        85
          1       0.89      0.91      0.90       132
          2       0.88      0.75      0.81        89
          3       0.83      0.70      0.76        90

avg / total       0.88      0.81      0.84       396

             precision    recall  f1-score   support

          0       0.91      0.82      0.86        84
          1       0.87      0.85      0.86       124
          2       0.96      0.93      0.95       115
          3       0.90      0.77      0.83        73

avg / total       0.91      0.85      0.88       396

             precision    recall  f1-score   support

          0       0.92      0.88      0.90       107
          1       0.87      0.82      0.85       137
          2       0.97      0.84      0.90        77
          3       0.82      0.87      0.84        75

avg / total       0.89      0.85      0.87       396

             precision    recall  f1-

In [3]:
corpus = list()
ylabels = list()
test = list()

path = '/home/clau/Documents/journalists2017_personas/emotions/'

f = codecs.open(path+'full_train.txt', 'r')
for line in f:
    corpus.append(line.strip())
f.close()

f1 = codecs.open(path+'full_target.txt', 'r')
for line in f1:
    thisLine = list()
    thisLine.append(line.strip())
    ylabels.append(thisLine)
f1.close()


In [4]:
X = np.array(corpus)
y = np.array(ylabels)

In [5]:
y

array([['1'],
       ['4'],
       ['3'],
       ..., 
       ['3'],
       ['4'],
       ['3']],
      dtype='<U1')

In [6]:
lb = preprocessing.MultiLabelBinarizer()
Y = lb.fit_transform(ylabels)

In [7]:
lb.classes_

array(['1', '2', '3', '4'], dtype=object)

In [8]:
y[0]

array(['1'],
      dtype='<U1')

In [9]:
Y[0]

array([1, 0, 0, 0])

In [10]:
model = RandomForestClassifier(n_estimators=500, random_state=0, criterion='entropy', min_samples_leaf=1, bootstrap=False)

classifier = Pipeline(
    [
        ('vectorizer', CountVectorizer(analyzer='word', stop_words='english')),
        ('tfidf', TfidfTransformer()),
        ('clf', model)
    ])

# Grid Search

In [60]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

# Utility function to report best scores
def report(results, n_top=3):
    for i in range(1, n_top + 1):
        candidates = np.flatnonzero(results['rank_test_score'] == i)
        for candidate in candidates:
            print("Model with rank: {0}".format(i))
            print("Mean validation score: {0:.3f} (std: {1:.3f})".format(
                  results['mean_test_score'][candidate],
                  results['std_test_score'][candidate]))
            print("Parameters: {0}".format(results['params'][candidate]))
            print("")

# use a full grid over all parameters
param_grid = {"clf__max_depth": [3, None],
                "clf__max_features": [1, 3, 10],
                "clf__min_samples_split": [2, 3, 10],
                "clf__min_samples_leaf": [1, 3, 10],
                "clf__bootstrap": [True, False],
                "clf__criterion": ["gini", "entropy"]}

model = RandomForestClassifier(n_estimators=25)

classifier = Pipeline(
    [
        ('vectorizer', CountVectorizer()),
        ('tfidf', TfidfTransformer()),
        ('clf', model)
    ])

# run grid search
grid_search = GridSearchCV(classifier, param_grid=param_grid)
start = time()
grid_search.fit(X_train, y_train)

print("GridSearchCV took %.2f seconds for %d candidate parameter settings."
      % (time() - start, len(grid_search.cv_results_['params'])))
report(grid_search.cv_results_)

GridSearchCV took 173.39 seconds for 216 candidate parameter settings.
Model with rank: 1
Mean validation score: 0.409 (std: 0.006)
Parameters: {'clf__min_samples_split': 2, 'clf__max_depth': None, 'clf__max_features': 10, 'clf__criterion': 'entropy', 'clf__min_samples_leaf': 1, 'clf__bootstrap': False}

Model with rank: 2
Mean validation score: 0.397 (std: 0.007)
Parameters: {'clf__min_samples_split': 2, 'clf__max_depth': None, 'clf__max_features': 10, 'clf__criterion': 'gini', 'clf__min_samples_leaf': 1, 'clf__bootstrap': False}

Model with rank: 3
Mean validation score: 0.392 (std: 0.012)
Parameters: {'clf__min_samples_split': 3, 'clf__max_depth': None, 'clf__max_features': 10, 'clf__criterion': 'entropy', 'clf__min_samples_leaf': 1, 'clf__bootstrap': False}



In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2)

In [21]:
model = RandomForestClassifier(n_estimators=150, random_state=0, criterion='entropy', min_samples_leaf=1, min_samples_split=2, n_jobs=4,bootstrap=False)

clasiffier = Pipeline(
    [
        ('vectorizer', CountVectorizer(analyzer='word', stop_words='english')),
        ('tfidf', TfidfTransformer()),
        ('clf1', model)
    ])

In [22]:
kf = KFold(n_splits=5, random_state=None, shuffle=False)
kf.get_n_splits(X) # returns the number of splitting iterations in the cross-validator

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y[train_index], Y[test_index]

    classifier.fit(X_train, y_train)
    y_predicted = classifier.predict(X_test)
    y_pred = lb.inverse_transform(y_predicted)
    print(classification_report(y_test, y_predicted))
    #print(y_pred)
    print('=========')
    break

             precision    recall  f1-score   support

          0       0.90      0.79      0.84       169
          1       0.89      0.83      0.86       256
          2       0.97      0.83      0.90       204
          3       0.82      0.73      0.77       163

avg / total       0.90      0.80      0.85       792

             precision    recall  f1-score   support

          0       0.93      0.74      0.82       201
          1       0.78      0.89      0.83       256
          2       0.98      0.84      0.91       172
          3       0.82      0.71      0.76       163

avg / total       0.87      0.80      0.83       792

             precision    recall  f1-score   support

          0       0.92      0.74      0.82       178
          1       0.95      0.74      0.83       253
          2       0.96      0.89      0.92       177
          3       0.73      0.77      0.75       184

avg / total       0.89      0.78      0.83       792

             precision    recall  f1-

In [127]:
classifier.fit(X_train, y_train)

Pipeline(memory=None,
     steps=[('vectorizer', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
       ...n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False))])

In [129]:
y_predicted = classifier.predict(X_test)

In [130]:
y_pred = lb.inverse_transform(y_predicted)

In [131]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_predicted))

             precision    recall  f1-score   support

          0       0.95      0.61      0.74       169
          1       0.94      0.79      0.86       256
          2       0.98      0.68      0.80       204
          3       0.89      0.58      0.70       163

avg / total       0.94      0.68      0.79       792



In [132]:
y_pred

[('1',),
 ('2',),
 (),
 ('4',),
 ('1',),
 ('2',),
 (),
 (),
 ('4',),
 ('1',),
 ('1',),
 ('1',),
 ('2',),
 ('2',),
 ('1',),
 (),
 (),
 ('1',),
 ('3',),
 (),
 ('1',),
 (),
 (),
 ('4',),
 (),
 ('2',),
 (),
 ('3',),
 ('2',),
 ('2',),
 ('3',),
 ('2',),
 (),
 (),
 (),
 ('2',),
 ('1',),
 ('1',),
 ('1',),
 (),
 (),
 ('4',),
 ('2',),
 ('4',),
 ('3',),
 ('2',),
 (),
 ('2',),
 ('1',),
 (),
 (),
 ('2',),
 (),
 ('3',),
 (),
 ('3',),
 ('2',),
 ('4',),
 (),
 ('2',),
 (),
 ('2',),
 ('4',),
 (),
 ('3',),
 ('4',),
 ('2',),
 ('1',),
 ('3',),
 ('3',),
 (),
 (),
 ('2',),
 ('3',),
 ('1',),
 ('1',),
 ('2',),
 (),
 (),
 (),
 ('4',),
 ('2',),
 ('2',),
 ('2',),
 (),
 ('3',),
 ('2',),
 ('2',),
 ('4',),
 ('2',),
 ('1',),
 ('1',),
 ('3',),
 ('2',),
 ('4',),
 ('4',),
 (),
 ('2',),
 ('3',),
 ('2',),
 ('2',),
 (),
 (),
 (),
 ('3',),
 ('2',),
 ('2',),
 ('4',),
 ('4',),
 ('3',),
 ('1',),
 ('2',),
 (),
 (),
 ('3',),
 (),
 (),
 ('1',),
 ('2',),
 ('2',),
 ('1',),
 (),
 ('2',),
 ('3',),
 ('2',),
 ('2',),
 ('2',),
 ('3',),


In [85]:
y_pred[0]

()

In [54]:
y_prob = classifier.predict_proba(X_test)

In [87]:
y_prob[0][0]

array([ 0.67,  0.33])

In [88]:
y_prob[1][0]

array([ 0.6188,  0.3812])

In [89]:
y_prob[2][0]

array([ 0.852,  0.148])

In [90]:
y_prob[3][0]

array([ 0.8592,  0.1408])

In [74]:
X_test.shape

(792,)

In [73]:
len(y_prob)

4

In [79]:
y_prob[3]

array([[ 0.8592    ,  0.1408    ],
       [ 0.93533333,  0.06466667],
       [ 0.885     ,  0.115     ],
       ..., 
       [ 0.85233333,  0.14766667],
       [ 0.97      ,  0.03      ],
       [ 0.826     ,  0.174     ]])

In [59]:
y_predicted[104]

array([ 0.,  0.,  0.,  1.])

In [80]:
y_prob[0][104]

array([ 0.978,  0.022])

In [81]:
y_prob[1][104]

array([ 0.956,  0.044])

In [82]:
y_prob[2][104]

array([ 0.918,  0.082])

In [83]:
y_prob[3][104]

array([ 0.148,  0.852])

In [47]:
classifier.classes_

[array([0, 1]), array([0, 1]), array([0, 1]), array([0, 1])]

In [ ]:
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y[train_index], Y[test_index]

    classifier.fit(X_train, y_train)
    predicted = classifier.predict(X_test)
    all_labels = lb.inverse_transform(predicted)

    for item, labels, true_labels in zip(X_test, all_labels, lb.inverse_transform(y_test)):
        #print('%s \t %s \t %s' % (item, ', '.join(labels), ', '.join(true_labels)))
        print('%s \t %s' % (', '.join(labels), ', '.join(true_labels)))


In [57]:
corpus = list()
ylabels = list()
test = list()

path = '/home/clau/Documents/journalists2017_personas/emotions/'

f = codecs.open(path+'full_train.txt', 'r')
for line in f:
    corpus.append(line.strip())
f.close()

f1 = codecs.open(path+'full_target.txt', 'r')
for line in f1:
    thisLine = list()
    thisLine.append(line.strip())
    ylabels.append(thisLine)
f1.close()

n_folds = 5

x = corpus

X = np.array(corpus)
y = np.array(ylabels)

lb = preprocessing.MultiLabelBinarizer()
Y = lb.fit_transform(ylabels)

svm = KNeighborsClassifier(n_neighbors=15, weights='uniform', algorithm='auto')

classifier = Pipeline([
        ('vectorizer', CountVectorizer()),
        ('tfidf', TfidfTransformer()),
        ('clf', OneVsRestClassifier(CalibratedClassifierCV(svm)))])

kf = KFold(n_splits=5)
kf.get_n_splits(X) # returns the number of splitting iterations in the cross-validator
KFold(n_splits=5, random_state=None, shuffle=False)

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y[train_index], Y[test_index]

    classifier.fit(X_train, y_train)
    predicted = classifier.predict(X_test)
    all_labels = lb.inverse_transform(predicted)

    for item, labels, true_labels in zip(X_test, all_labels, lb.inverse_transform(y_test)):
        #print('%s \t %s \t %s' % (item, ', '.join(labels), ', '.join(true_labels)))
        print('%s \t %s' % (', '.join(labels), ', '.join(true_labels)))


1 	 1
 	 4
 	 3
4 	 4
1 	 1
2 	 2
2 	 3
3 	 3
 	 4
1 	 1
1 	 1
1 	 1
2 	 2
2 	 2
1 	 1
 	 2
 	 4
 	 1
4 	 3
 	 1
1 	 1
 	 3
 	 4
 	 1
 	 2
2 	 2
 	 4
3 	 3
2 	 2
2 	 2
3 	 3
 	 3
1 	 1
 	 2
1 	 1
2 	 2
1 	 1
1 	 1
1 	 1
 	 3
 	 3
1 	 4
2 	 2
2 	 4
 	 3
2 	 2
3 	 4
 	 4
1 	 1
 	 4
 	 3
2 	 2
 	 1
3 	 3
 	 3
 	 3
2 	 2
 	 2
 	 1
2 	 2
 	 1
2 	 2
4 	 4
 	 1
3 	 3
4 	 2
2 	 2
 	 1
4 	 4
3 	 3
1 	 2
 	 3
2 	 2
 	 3
 	 1
1 	 1
 	 2
 	 4
2 	 1
 	 3
 	 4
4 	 4
2 	 2
2 	 2
 	 1
 	 3
2 	 2
 	 3
4 	 4
2 	 2
1 	 1
1 	 1
2 	 3
2 	 2
 	 4
4 	 4
2 	 1
2 	 2
 	 3
2 	 2
 	 2
1 	 1
2 	 2
3 	 4
3 	 3
4 	 2
2 	 2
4 	 4
1 	 1
3 	 3
1 	 1
4 	 2
3 	 3
4 	 3
3 	 3
 	 2
2 	 2
1 	 1
2 	 2
1 	 2
 	 4
 	 4
2 	 2
3 	 3
2 	 2
2 	 2
2 	 2
3 	 3
 	 4
2 	 2
 	 2
3 	 3
 	 4
4 	 4
1 	 1
3 	 3
3 	 3
 	 4
 	 4
4 	 4
 	 4
 	 2
4 	 4
 	 1
3 	 3
 	 1
1 	 1
 	 2
3 	 3
2 	 2
 	 3
4 	 3
3 	 3
4 	 4
3 	 2
 	 1
 	 1
 	 4
1 	 1
4 	 4
2 	 2
1 	 1
3 	 3
4 	 4
 	 2
1 	 1
2 	 2
 	 3
4 	 4
 	 2
4 	 4
 	 3
 	 3
 	 2
2 	 2
 	 2
 	 1
 	 3

In [33]:
corpus = list()
ylabels = list()
test = list()

path = '/home/clau/Documents/journalists2017_personas/emotions/'

f = codecs.open(path+'full_train.txt', 'r')
for line in f:
    corpus.append(line.strip())
f.close()

f1 = codecs.open(path+'full_target.txt', 'r')
for line in f1:
    thisLine = list()
    thisLine.append(line.strip())
    ylabels.append(thisLine)
f1.close()

X = np.array(corpus)
y = np.array(ylabels)

lb = preprocessing.MultiLabelBinarizer()
Y = lb.fit_transform(ylabels)

model = KNeighborsClassifier(n_neighbors=100)

classifier = Pipeline(
    [
        ('vectorizer', CountVectorizer()),
        ('tfidf', TfidfTransformer()),
        ('clf', OneVsRestClassifier(CalibratedClassifierCV(model)))
    ])

kf = KFold(n_splits=10, random_state=None, shuffle=False)
kf.get_n_splits(X) # returns the number of splitting iterations in the cross-validator

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = Y[train_index], Y[test_index]

    classifier.fit(X_train, y_train)
    y_predicted = classifier.predict(X_test)
    y_pred = lb.inverse_transform(y_predicted)
    print(classification_report(y_test, y_predicted))
    #print(y_pred)
    print('=========')

             precision    recall  f1-score   support

          0       0.80      0.53      0.64        85
          1       0.83      0.64      0.72       132
          2       0.83      0.38      0.52        89
          3       0.83      0.39      0.53        90

avg / total       0.83      0.50      0.62       396

             precision    recall  f1-score   support

          0       0.72      0.51      0.60        84
          1       0.81      0.57      0.67       124
          2       0.82      0.46      0.59       115
          3       0.88      0.41      0.56        73

avg / total       0.80      0.50      0.61       396

             precision    recall  f1-score   support

          0       0.86      0.50      0.64       107
          1       0.82      0.65      0.72       137
          2       0.76      0.45      0.57        77
          3       0.76      0.45      0.57        75

avg / total       0.81      0.54      0.64       396

             precision    recall  f1-